//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class BatchSumup
    {
        public int BatchID { get; set; }
        public Nullable<int> CartonCounts { get; set; }
        public int FillingLineID { get; set; }
        public string BatchCode { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public int UniqueCartonCounts { get; set; }
        public string CommodityOfficialCode { get; set; }
        public int UniqueCheckedOut { get; set; }
    }
}
