//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class BatchMaxNo
    {
        public string NextPackNo { get; set; }
        public string BatchPackNo { get; set; }
        public string NextCartonNo { get; set; }
        public string BatchCartonNo { get; set; }
        public string NextPalletNo { get; set; }
        public string BatchPalletNo { get; set; }
    }
}
