//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class BinLocationIndex
    {
        public int BinLocationID { get; set; }
        public string Remarks { get; set; }
        public string BinLocationCode { get; set; }
        public string BinLocationName { get; set; }
        public string LocationName { get; set; }
        public bool InActive { get; set; }
    }
}
