//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class CartonAttribute
    {
        public int CartonID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int FillingLineID { get; set; }
        public string FillingLineCode { get; set; }
        public string FillingLineName { get; set; }
        public int BatchID { get; set; }
        public System.DateTime BatchEntryDate { get; set; }
        public string BatchCode { get; set; }
        public int LocationID { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string OfficialCode { get; set; }
        public string CommodityName { get; set; }
        public Nullable<int> PalletID { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public decimal Quantity { get; set; }
        public decimal LineVolume { get; set; }
        public int PackCounts { get; set; }
        public int EntryStatusID { get; set; }
        public int SubmitStatusID { get; set; }
        public string Remarks { get; set; }
    }
}
