//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnMapping
    {
        public int ColumnMappingID { get; set; }
        public int MappingTaskID { get; set; }
        public int ColumnID { get; set; }
        public string ColumnName { get; set; }
        public string ColumnDisplayName { get; set; }
        public string ColumnMappingName { get; set; }
        public int SerialID { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public System.DateTime ImportedDate { get; set; }
    }
}
