//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class CommoditySettingIndex
    {
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public Nullable<decimal> LowDSI1 { get; set; }
        public Nullable<decimal> HighDSI1 { get; set; }
        public Nullable<decimal> AlertDSI1 { get; set; }
        public Nullable<decimal> LowDSI2 { get; set; }
        public Nullable<decimal> HighDSI2 { get; set; }
        public Nullable<decimal> AlertDSI2 { get; set; }
        public Nullable<decimal> LowDSI3 { get; set; }
        public Nullable<decimal> HighDSI3 { get; set; }
        public Nullable<decimal> AlertDSI3 { get; set; }
        public Nullable<decimal> LowDSI4 { get; set; }
        public Nullable<decimal> HighDSI4 { get; set; }
        public Nullable<decimal> AlertDSI4 { get; set; }
        public int CommodityCategoryID { get; set; }
        public string CommodityCategoryName { get; set; }
        public string PackageSize { get; set; }
        public decimal PackageVolume { get; set; }
        public int CommoditySettingID { get; set; }
    }
}
