//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class CommodityTypeTree
    {
        public Nullable<int> NodeID { get; set; }
        public Nullable<int> ParentNodeID { get; set; }
        public Nullable<int> PrimaryID { get; set; }
        public Nullable<int> AncestorID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ParameterName { get; set; }
        public Nullable<bool> Selected { get; set; }
    }
}
