//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommoditySettingDetail
    {
        public int CommoditySettingDetailID { get; set; }
        public int CommoditySettingID { get; set; }
        public int CommodityID { get; set; }
        public int LocationID { get; set; }
        public int SettingLocationID { get; set; }
        public decimal LowDSI { get; set; }
        public decimal HighDSI { get; set; }
        public decimal AlertDSI { get; set; }
    
        public virtual CommoditySetting CommoditySetting { get; set; }
        public virtual Commodity Commodity { get; set; }
    }
}
