//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class CustomerBase
    {
        public int CustomerID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ContactInfo { get; set; }
        public int SalespersonID { get; set; }
        public string ShippingAddress { get; set; }
    }
}
