//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class CustomerIndex
    {
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerOfficialName { get; set; }
        public string ContactInfo { get; set; }
        public string BillingAddress { get; set; }
        public int TerritoryID { get; set; }
        public string EntireTerritoryEntireName { get; set; }
        public int EmployeeID { get; set; }
        public string SalespersonName { get; set; }
        public bool InActive { get; set; }
    }
}
