//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class FillingLineIndex
    {
        public int FillingLineID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string FillingLineType { get; set; }
    }
}
