//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FillingLineDetail
    {
        public int FillingLineDetailID { get; set; }
        public int FillingLineID { get; set; }
        public int DeviceID { get; set; }
        public int IPv4Byte1 { get; set; }
        public int IPv4Byte2 { get; set; }
        public int IPv4Byte3 { get; set; }
        public int IPv4Byte4 { get; set; }
    
        public virtual FillingLine FillingLine { get; set; }
        public virtual Device Device { get; set; }
    }
}
