//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Forecast()
        {
            this.ForecastDetails = new HashSet<ForecastDetail>();
        }
    
        public int ForecastID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
        public string VoucherCode { get; set; }
        public int ForecastLocationID { get; set; }
        public int UserID { get; set; }
        public int PreparedPersonID { get; set; }
        public int OrganizationalUnitID { get; set; }
        public int LocationID { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalLineVolume { get; set; }
        public decimal TotalQuantityM1 { get; set; }
        public decimal TotalLineVolumeM1 { get; set; }
        public decimal TotalQuantityM2 { get; set; }
        public decimal TotalLineVolumeM2 { get; set; }
        public decimal TotalQuantityM3 { get; set; }
        public decimal TotalLineVolumeM3 { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EditedDate { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public int QuantityVersusVolume { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForecastDetail> ForecastDetails { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
    }
}
