//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class ModuleViewDetail
    {
        public int ModuleID { get; set; }
        public string Actions { get; set; }
        public string Controller { get; set; }
        public double LastOpen { get; set; }
        public double SerialID { get; set; }
        public string ImageIndex { get; set; }
        public double InActive { get; set; }
        public int ModuleDetailID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
    }
}
