//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class OrganizationalUnitIndex
    {
        public int OrganizationalUnitID { get; set; }
        public string OrganizationalUnitName { get; set; }
        public string LocationName { get; set; }
        public string LocationOrganizationalUnitName { get; set; }
        public int LocationID { get; set; }
    }
}
