//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class PendingDeliveryAdvice
    {
        public int DeliveryAdviceID { get; set; }
        public string DeliveryAdviceReference { get; set; }
        public System.DateTime DeliveryAdviceEntryDate { get; set; }
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string SalesOrderReferences { get; set; }
        public string VoucherCode { get; set; }
        public int ReceiverID { get; set; }
        public string ReceiverCode { get; set; }
        public string ReceiverName { get; set; }
        public int ForkliftDriverID { get; set; }
        public int StorekeeperID { get; set; }
        public string Vehicle { get; set; }
        public string VehicleDriver { get; set; }
    }
}
