//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class PendingTransferOrder
    {
        public int TransferOrderID { get; set; }
        public string TransferOrderReference { get; set; }
        public System.DateTime TransferOrderEntryDate { get; set; }
        public string VoucherCode { get; set; }
        public int WarehouseReceiptID { get; set; }
        public string WarehouseReceiptCode { get; set; }
        public string WarehouseReceiptName { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string TransferJobs { get; set; }
        public int WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public int ForkliftDriverID { get; set; }
        public int StorekeeperID { get; set; }
        public string Vehicle { get; set; }
        public string VehicleDriver { get; set; }
        public int LocationReceiptID { get; set; }
    }
}
