//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class UserControlAvailableGroup
    {
        public int UserGroupID { get; set; }
        public string Description { get; set; }
        public string UserGroup { get; set; }
        public string GroupCode { get; set; }
        public string GroupName { get; set; }
    }
}
