//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class UserControlGroup
    {
        public int UserGroupDetailID { get; set; }
        public int UserGroupID { get; set; }
        public string UserGroupCode { get; set; }
        public string UserGroupName { get; set; }
        public string GroupType { get; set; }
    }
}
