//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webapi
    {
        public int WebapiID { get; set; }
        public string BaseUri { get; set; }
        public string ConsumerKey { get; set; }
        public string ConsumerSecret { get; set; }
        public System.DateTime EditedDate { get; set; }
    }
}
